apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flogo-hello-world
  description: Flogo version of hello-world
  annotations:
    github.com/project-slug: mmussett/flogo-hello-world
spec:
  type: service
  lifecycle: experimental
  owner: flogo-developers
  providesApis:
    - flogo-hello-world-api
--- 
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: flogo-developers
  description: TIBCO Flogo Developer Group
spec:
  type: organization
  profile:
    displayName: Flogo Developers
    email: mmussett@tibco.com
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: flogo-hello-world-api-location
spec:
  targets:
    - ./api-info.yaml