apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: flogo-developers
  description: TIBCO Flogo Developer Group
spec:
  type: organization
  profile:
    displayName: Flogo Developers
    email: mmussett@tibco.com
  children: []