# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Flogo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      CP_BASE_URL: https://tibcoatseuce1.eu-west.my.tibco.com
      DP_BASE_URL: https://devhub.vmlab.live/tibco/flogo/cpol44ihntso8gmhn1u0/public
      TOKEN: ${{secrets.TOKEN}}
      APP_JSON: flogo-hello-world.flogo
      TARGET_ARCH: amd64
      TARGET_OS: linux
      PROVISIONER_BUILD_WAIT_INTERVAL: 60
      PROVISIONER_DEPLOY_WAIT_INTERVAL: 60
      PROVISIONER_DELETE_WAIT_INTERVAL: 25
      PROVISIONER_SCALE_WAIT_INTERVAL: 60
      PROVISIONER_SERVICE_MESH_WAIT_INTERVAL: 25
      PROVISIONER_PUBLIC_ENDPOINT_INTERVAL: 25

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4

    - name: Build and deploy 
      run: ant -noinput -buildfile build.xml init clean build deploy enable-service-mesh enable-public-endpoints