# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Flogo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      BASE_URL: devhub.vmlab.live/tibco/flogo/cpol44ihntso8gmhn1u0/public
      TOKEN: ${{secrets.TOKEN}}
      APP_JSON: flogo-hello-world.flogo
      APP_ID: cpoo4ckikhfajg2sgs1g
      TARGET_ARCH: amd64
      TARGET_OS: linux

      
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4

    - name: Building app executable using application json 
      run: ant -noinput -buildfile build.xml clean build 
